apiVersion: v1
kind: Pod
metadata:
  name: helloworld-hostpath
  labels:
    name: helloworld-hostpath
spec:
  containers:
  - name: my-hello
    image: mehradi/my-hello
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
    volumeMounts:
      - mountPath: /test-mnt
        name: test-vol
  volumes:
    - name: test-vol
      hostPath:
        path: /test-vol